# editing/captions.py

CAPTIONS = [
    "Like if you picked the wrong one 💀",
    "Follow for more 1v1 chaos 🔥",
    "Just bots being bots 🤖",
    "Yes, this was completely random. No, I’m not fixing it.",
    "Who wins this one? 👀",
    "Place your bets! 🔮",
    "Red or Blue? 🤔 Comment below!",
    "I swear this one’s rigged 💀",
    "Don’t scroll... just watch. Trust me.",
    "Only 1% guess right 😈",
    "Winner gets bragging rights — who you got?",
    "Comment ‘🟥’ or ‘🟦’ before the end!",
    "Wait for it… 😳",
    "It gets wild at the end!",
    "Watch twice. It’s different.",
    "You missed it. Watch again 🔁",
    "I still don’t get what happened 🧠",
    "Rewatch if you blinked 👁️",
    "Loop or skill? You decide.",
    "Was that fair?? 😤",
    "This actually made me mad…",
    "One of them CHEATED.",
    "What would you have done?",
    "Tag someone who needs to see this",
    "Real skill or pure luck?",
    "Bots be like: 😐",
    "Like if your friend would lose this",
    "This game is way too close 😬",
    "Who made this?? LMAO",
    "I didn’t see that coming...",
    "Unpredictable. Every time.",
    "He had ONE job...",
    "The ending caught me off guard 😭",
    "I need answers. NOW.",
    "Tell me this isn’t scripted.",
    "This should be illegal 😭",
    "Absolute chaos from the start.",
    "Watch till the end. You won’t regret it.",
    "Bots got beef 💢",
    "No way that was random 😂",
    "This game deserves a rematch",
    "Instant replay needed 📽️",
    "I can't stop watching this 🤯",
    "Who made these maniacs?",
    "That ending though... 😳",
    "Are they learning?? 😳",
    "It’s like they KNOW. 🤖",
    "This is cursed ☠️",
    "Why does this feel personal?",
    "Skill issue? 🤔",
    "Plot twist: you blinked and missed it",
    "Don’t lie. You watched it twice.",
    "I dare you to guess the winner",
    "No one saw that coming",
    "One of them cheated, right?",
    "This should be a movie",
    "Peak entertainment 😤",
    "10/10 would watch again",
    "You’ve been warned. It’s addictive.",
    "Don’t scroll. Pick a side.",
    "You VS the bot she told you not to worry about",
    "They understood the assignment 🤝",
    "I coded this and I’m still confused",
    "Imagine losing like that 😬",
    "This was personal for them 😤",
    "Speed. Power. Chaos.",
    "This is what nightmares are made of",
    "Bots just ended your whole career",
    "Funniest ending I’ve ever seen 😂",
    "This had no business going this hard",
    "Absolute domination 💥",
    "Justice was served 🧑‍⚖️",
    "He woke up and chose violence",
    "Survival of the glitchiest",
    "The comeback was real",
    "Nothing makes sense anymore",
    "Name a better duo. I’ll wait.",
    "You blinked, didn’t you?",
    "Just another day in the simulation",
    "I still don’t understand how they won",
    "RIP to the loser 💀",
    "It’s giving Final Destination vibes",
    "Comment if you guessed right",
    "This aged like milk 🥴",
    "Certified bot moment 🤖",
    "Not even the devs could predict this",
    "I’m questioning reality right now",
    "This is oddly satisfying",
    "Battle of the century",
    "Would you bet your lunch money on this?",
    "Who trained these bots?",
    "That was violent 😮",
    "Comment 🧠 if you predicted that",
    "Straight outta simulation",
    "Tag a friend who would lose this",
    "It’s like watching toddlers fight 🤣",
    "Bro forgot how to game",
    "It went from 0 to 100 real quick",
    "I watched this 5 times. Still funny.",
    "Did he just phase through that??",
    "Final boss behavior",
    "They knew the assignment... too well.",
    "Whoever made this needs therapy",
    "No thoughts, just violence",
    "Bots ain’t loyal 💔",
    "I have no words. Just watch."
]